version: "3.8"

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn run start:prod
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=idea-meeting
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
    driver: bridge
#docker-compose -f docker-compose.dev.yml up -d postgres
#
